title: Ashlynn Blanshan
description: I am an aspiring data scientist from Michigan State University interested in Machine Learning, AI, and much more! This is my data science portfolio showcasing my education, previous work experience, and data science projects.
theme : jekyll-theme-minimal
